#ifndef __TAGS___
#define __TAGS___
#include <unordered_map>
#include <string>

std::unordered_map<int, std::string> tagsList = {
    { 0x06, "Object Identifier (OID)" },
    { 0x41, "Country code and national data" },
    { 0x42, "Issuer Identification Number (IIN)" },
    { 0x42, "Issuer Identification Number (IIN)" },
    { 0x43, "Card service data" },
    { 0x44, "Initial access data" },
    { 0x45, "Card issuer`s data" },
    { 0x46, "Pre-issuing data" },
    { 0x47, "Card capabilities" },
    { 0x48, "Status information" },
    { 0x4D, "Extended header list" },
    { 0x4F, "Application Identifier (ADF Name)" },
    { 0x50, "Application Label" },
    { 0x50, "Application Label" },
    { 0x50, "Application Label" },
    { 0x51, "Path" },
    { 0x52, "Command to perform" },
    { 0x53, "Discretionary data, discretionary template" },
    { 0x56, "Track 1 Data" },
    { 0x56, "Track 1 Equivalent Data" },
    { 0x57, "Track 2 Equivalent Data" },
    { 0x57, "Track 2 Equivalent Data" },
    { 0x57, "Track 2 Equivalent Data" },
    { 0x57, "Track 2 Equivalent Data" },
    { 0x57, "Track 2 Equivalent Data" },
    { 0x58, "Track 3 Equivalent Data" },
    { 0x59, "Card expiration date" },
    { 0x5A, "Application Primary Account Number (PAN)" },
    { 0x5A, "Application Primary Account Number (PAN)" },
    { 0x5A, "Application Primary Account Number (PAN)" },
    { 0x5A, "Application Primary Account Number (PAN)" },
    { 0x5B, "Name of an individual" },
    { 0x5C, "Tag list" },
    { 0x5D, "Deleted (see 9D)" },
    { 0x5D, "Header list" },
    { 0x5E, "Proprietary login data" },
    { 0x5F20, "Cardholder Name" },
    { 0x5F20, "Cardholder Name" },
    { 0x5F20, "Cardholder Name" },
    { 0x5F20, "Cardholder Name" },
    { 0x5F21, "Track 1, identical to the data coded" },
    { 0x5F22, "Track 2, identical to the data coded" },
    { 0x5F23, "Track 3, identical to the data coded" },
    { 0x5F24, "Application Expiration Date" },
    { 0x5F24, "Application Expiration Date" },
    { 0x5F24, "Application Expiration Date" },
    { 0x5F24, "Application Expiration Date" },
    { 0x5F25, "Application Effective Date" },
    { 0x5F25, "Application Effective Date" },
    { 0x5F25, "Application Effective Date" },
    { 0x5F26, "Date, Card Effective" },
    { 0x5F27, "Interchange control" },
    { 0x5F28, "Issuer Country Code" },
    { 0x5F28, "Issuer Country Code" },
    { 0x5F28, "Issuer Country Code" },
    { 0x5F28, "Issuer Country Code" },
    { 0x5F29, "Interchange profile" },
    { 0x5F2A, "Transaction Currency Code" },
    { 0x5F2A, "Transaction Currency Code" },
    { 0x5F2A, "Transaction Currency Code" },
    { 0x5F2A, "Transaction Currency Code" },
    { 0x5F2A, "Transaction Currency Code" },
    { 0x5F2B, "Date of birth" },
    { 0x5F2C, "Cardholder nationality" },
    { 0x5F2D, "Language Preference" },
    { 0x5F2D, "Language Preference" },
    { 0x5F2D, "Language Preference" },
    { 0x5F2E, "Cardholder biometric data" },
    { 0x5F2F, "PIN usage policy" },
    { 0x5F30, "Service Code" },
    { 0x5F30, "Service Code" },
    { 0x5F32, "Transaction counter" },
    { 0x5F33, "Date, Transaction" },
    { 0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)" },
    { 0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)" },
    { 0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)" },
    { 0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)" },
    { 0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)" },
    { 0x5F35, "Sex (ISO 5218)" },
    { 0x5F36, "Transaction Currency Exponent" },
    { 0x5F36, "Transaction Currency Exponent" },
    { 0x5F37, "Static internal authentication (one-step)" },
    { 0x5F38, "Static internal authentication - first associated data" },
    { 0x5F39, "Static internal authentication - second associated data" },
    { 0x5F3A, "Dynamic internal authentication" },
    { 0x5F3B, "Dynamic external authentication" },
    { 0x5F3C, "Transaction Reference Currency Code" },
    { 0x5F3C, "Dynamic mutual authentication" },
    { 0x5F3D, "Transaction Reference Currency Exponent" },
    { 0x5F40, "Cardholder portrait image" },
    { 0x5F41, "Element list" },
    { 0x5F42, "Address" },
    { 0x5F43, "Cardholder handwritten signature image" },
    { 0x5F44, "Application image" },
    { 0x5F45, "Display message" },
    { 0x5F46, "Timer" },
    { 0x5F47, "Message reference" },
    { 0x5F48, "Cardholder private key" },
    { 0x5F49, "Cardholder public key" },
    { 0x5F4A, "Public key of certification authority" },
    { 0x5F4B, "Deprecated (see note 2 below)" },
    { 0x5F4C, "Certificate holder authorization" },
    { 0x5F4D, "Integrated circuit manufacturer identifier" },
    { 0x5F4E, "Certificate content" },
    { 0x5F50, "Issuer Uniform resource locator (URL)" },
    { 0x5F53, "International Bank Account Number (IBAN)" },
    { 0x5F54, "Bank Identifier Code (BIC)" },
    { 0x5F55, "Issuer Country Code (alpha2 format)" },
    { 0x5F56, "Issuer Country Code (alpha3 format)" },
    { 0x5F57, "Account Type" },
    { 0x60, "Template, Dynamic Authentication" },
    { 0x6080, "Commitment (e.g., a positive number less than the public RSA modulus in use)" },
    { 0x6081, "Challenge (e.g., a number, possibly zero, less than the public RSA exponent in use)" },
    { 0x6082, "Response (e.g., a positive number less than the public RSA modulus in use)" },
    { 0x6083, "Committed challenge (e.g., the hash-code of a commitment data object)" },
    { 0x6084, "Authentication code (e.g., the hash-code of one or more data fields and a commitment data object)" },
    { 0x6085, "Exponential (e.g., a public positive number for establishing a session key by a DH method)" },
    { 0x60A0, "Template, Identification data" },
    { 0x61, "Application Template" },
    { 0x61, "Directory Entry" },
    { 0x62, "File Control Parameters (FCP) Template" },
    { 0x6280, "Number of data bytes in the file, excluding structural information" },
    { 0x6281, "Number of data bytes in the file, including structural information if any" },
    { 0x6282, "File descriptor byte" },
    { 0x6283, "File identifier" },
    { 0x6284, "DF name" },
    { 0x6285, "Proprietary information, primitive encoding (i.e., not coded in BER-TLV)" },
    { 0x6286, "Security attribute in proprietary format" },
    { 0x6287, "Identifier of an EF containing an extension of the file control information" },
    { 0x6288, "Short EF identifier" },
    { 0x628A, "Life cycle status byte (LCS)" },
    { 0x628B, "Security attribute referencing the expanded format" },
    { 0x628C, "Security attribute in compact format" },
    { 0x628D, "Identifier of an EF containing security environment templates" },
    { 0x62A0, "Template, Security attribute for data objects" },
    { 0x62A1, "Template, Security attribute for physical interfaces" },
    { 0x62A2, "One or more pairs of data objects, short EF identifier (tag 88) - absolute or relative path (tag 51)" },
    { 0x62A5, "Proprietary information, constructed encoding" },
    { 0x62AB, "Security attribute in expanded format" },
    { 0x62AC, "Identifier of a cryptographic mechanism" },
    { 0x63, "Wrapper" },
    { 0x64, "Template, File Management Data (FMD)" },
    { 0x65, "Cardholder related data" },
    { 0x66, "Template, Card data" },
    { 0x67, "Template, Authentication data" },
    { 0x68, "Special user requirements" },
    { 0x6A, "Template, Login" },
    { 0x6A80, "Qualifier" },
    { 0x6A81, "Telephone Number" },
    { 0x6A82, "Text" },
    { 0x6A83, "Delay indicators, for detecting an end of message" },
    { 0x6A84, "Delay indicators, for detecting an absence of response" },
    { 0x6B, "Template, Qualified name" },
    { 0x6B06, "Qualified name" },
    { 0x6B80, "Name" },
    { 0x6BA0, "Name" },
    { 0x6C, "Template, Cardholder image" },
    { 0x6D, "Template, Application image" },
    { 0x6E, "Application related data" },
    { 0x6F, "File Control Information (FCI) Template" },
    { 0x6F, "File Control Information (FCI) Template" },
    { 0x6F, "File Control Information (FCI) Template" },
    { 0x6F, "Template, File Control Parameters and File Management Data (FCI)" },
    { 0x6FA5, "Template, FCI A5" },
    { 0x70, "READ RECORD Response Message Template" },
    { 0x70, "READ RECORD Response Message Template" },
    { 0x70, "Template, AEF Data" },
    { 0x71, "Issuer Script Template 1" },
    { 0x71, "Issuer Script Template 1" },
    { 0x71, "Template, Issuer Script 1" },
    { 0x7186, "Issuer Script Command" },
    { 0x719F18, "Issuer Script Identifier" },
    { 0x72, "Issuer Script Template 2" },
    { 0x72, "Issuer Script Template 2" },
    { 0x72, "Template, Issuer Script 2" },
    { 0x73, "Directory Discretionary Template" },
    { 0x77, "Response Message Template Format 2" },
    { 0x77, "Response Message Template Format 2" },
    { 0x77, "Response Message Template Format 2" },
    { 0x77, "Template, Response Message Format 2" },
    { 0x78, "Compatible Tag Allocation Authority" },
    { 0x79, "Coexistent Tag Allocation Authority" },
    { 0x7A, "Template, Security Support (SS)" },
    { 0x7A80, "Card session counter" },
    { 0x7A81, "Session identifier" },
    { 0x7A82, "File selection counter" },
    { 0x7A83, "File selection counter" },
    { 0x7A84, "File selection counter" },
    { 0x7A85, "File selection counter" },
    { 0x7A86, "File selection counter" },
    { 0x7A87, "File selection counter" },
    { 0x7A88, "File selection counter" },
    { 0x7A89, "File selection counter" },
    { 0x7A8A, "File selection counter" },
    { 0x7A8B, "File selection counter" },
    { 0x7A8C, "File selection counter" },
    { 0x7A8D, "File selection counter" },
    { 0x7A8E, "File selection counter" },
    { 0x7A93, "Digital signature counter" },
    { 0x7A9F2,"Internal progression value ('X'-is a specific index, e.g., an index referencing a counter of file selections)" },
    { 0x7A9F3,"External progression value ('Y'-is a specific index, e.g., an index referencing an external time stamp)" },
    { 0x7B, "Template, Security Environment (SE)" },
    { 0x7B80, "SEID byte, mandatory" },
    { 0x7B8A, "LCS byte, optional" },
    { 0x7BAC, "Cryptographic mechanism identifier template, optional" },
    { 0x7BA4, "Control reference template (CRT)" },
    { 0x7BAA, "Control reference template (CRT)" },
    { 0x7BB4, "Control reference template (CRT)" },
    { 0x7BB6, "Control reference template (CRT)" },
    { 0x7BB8, "Control reference template (CRT)" },
    { 0x7D, "Template, Secure Messaging (SM)" },
    { 0x7D80, "Plain value not coded in BER-TLV" },
    { 0x7D81, "Plain value not coded in BER-TLV" },
    { 0x7D82, "Cryptogram (plain value coded in BER-TLV and including secure messaging data objects)" },
    { 0x7D83, "Cryptogram (plain value coded in BER-TLV and including secure messaging data objects)" },
    { 0x7D84, "Cryptogram (plain value coded in BER-TLV, but not including secure messaging data objects)" },
    { 0x7D85, "Cryptogram (plain value coded in BER-TLV, but not including secure messaging data objects)" },
    { 0x7D86, "Padding-content indicator byte followed by cryptogram (plain value not coded in BER-TLV)" },
    { 0x7D87, "Padding-content indicator byte followed by cryptogram (plain value not coded in BER-TLV)" },
    { 0x7D8E, "Cryptographic checksum (at least four bytes)" },
    { 0x7D90, "Hash-code" },
    { 0x7D91, "Hash-code" },
    { 0x7D92, "Certificate (not BER-TLV coded data)" },
    { 0x7D93, "Certificate (not BER-TLV coded data)" },
    { 0x7D94, "Security environment identifier (SEID byte, see 6.5)" },
    { 0x7D95, "Security environment identifier (SEID byte, see 6.5)" },
    { 0x7D96, "Number Le in the unsecured command APDU (one or two bytes)" },
    { 0x7D97, "Number Le in the unsecured command APDU (one or two bytes)" },
    { 0x7D99, "Processing status of the secured response APDU (new SW1-SW2, two bytes)" },
    { 0x7D9A, "Input data element for the computation of a digital signature (the value field is signed)" },
    { 0x7D9B, "Input data element for the computation of a digital signature (the value field is signed)" },
    { 0x7D9C, "Public key" },
    { 0x7D9D, "Public key" },
    { 0x7D9E, "Digital signature" },
    { 0x7DA0, "Input template for the computation of a hash-code (the template is hashed)" },
    { 0x7DA1, "Input template for the computation of a hash-code (the template is hashed)" },
    { 0x7DA2, "Input template for the verification of a cryptographic checksum (the template is integrated)" },
    { 0x7DA4, "Control reference template for authentication (AT)" },
    { 0x7DA5, "Control reference template for authentication (AT)" },
    { 0x7DA8, "Input template for the verification of a digital signature (the template is signed)" },
    { 0x7DAA, "Template, Control reference for hash-code (HT)" },
    { 0x7DAB, "Template, Control reference for hash-code (HT)" },
    { 0x7DAC, "Input template for the computation of a digital signature (the concatenated value fields are signed)" },
    { 0x7DAD, "Input template for the computation of a digital signature (the concatenated value fields are signed)" },
    { 0x7DAE, "Input template for the computation of a certificate (the concatenated value fields are certified)" },
    { 0x7DAF, "Input template for the computation of a certificate (the concatenated value fields are certified)" },
    { 0x7DB0, "Plain value coded in BER-TLV and including secure messaging data objects" },
    { 0x7DB1, "Plain value coded in BER-TLV and including secure messaging data objects" },
    { 0x7DB2, "Plain value coded in BER-TLV, but not including secure messaging data objects" },
    { 0x7DB3, "Plain value coded in BER-TLV, but not including secure messaging data objects" },
    { 0x7DB4, "Control reference template for cryptographic checksum (CCT)" },
    { 0x7DB5, "Control reference template for cryptographic checksum (CCT)" },
    { 0x7DB6, "Control reference template for digital signature (DST)" },
    { 0x7DB7, "Control reference template for digital signature (DST)" },
    { 0x7DB8, "Control reference template for confidentiality (CT)" },
    { 0x7DB9, "Control reference template for confidentiality (CT)" },
    { 0x7DBA, "Response descriptor template" },
    { 0x7DBB, "Response descriptor template" },
    { 0x7DBC, "Input template for the computation of a digital signature (the template is signed)" },
    { 0x7DBD, "Input template for the computation of a digital signature (the template is signed)" },
    { 0x7DBE, "Input template for the verification of a certificate (the template is certified)" },
    { 0x7E, "Template, Nesting Interindustry data objects" },
    { 0x7F20, "Display control template" },
    { 0x7F21, "Cardholder certificate" },
    { 0x7F2E, "Biometric data template" },
    { 0x7F49, "Template, Cardholder public key" },
    { 0x7F4980, "Algorithm reference as used in control reference data objects for secure messaging" },
    { 0x7F4981,
      "RSA Modulus (a number denoted as n coded on x bytes), or DSA First prime (a number denoted as p coded on y "
      "bytes), or ECDSA Prime (a number denoted as p coded on z bytes)" },
    { 0x7F4982,
      "RSA Public exponent (a number denoted as v, e.g., 65537), or DSA Second prime (a number denoted as q dividing "
      "p-1, e.g., 20 bytes), or ECDSA First coefficient (a number denoted as a coded on z bytes)" },
    { 0x7F4983,
      "DSA Basis (a number denoted as g of order q coded on y bytes), or ECDSA Second coefficient (a number denoted as "
      "b coded on z bytes)" },
    { 0x7F4984,
      "DSA Public key (a number denoted as y equal to g to the power x mod p where x is the private key coded on y "
      "bytes), or ECDSA Generator (a point denoted as PB on the curve, coded on 2z bytes)" },
    { 0x7F4985, "ECDSA Order (a prime number denoted as q, order of the generator PB, coded on z bytes)" },
    { 0x7F4986,
      "ECDSA Public key (a point denoted as PP on the curve, equal to x times PB where x is the private key, coded on "
      "2z bytes)" },
    { 0x7F4C, "Template, Certificate Holder Authorization" },
    { 0x7F4E, "Certificate Body" },
    { 0x7F4E42, "Certificate Authority Reference" },
    { 0x7F4E5F20, "Certificate Holder Reference" },
    { 0x7F4E5F24, "Expiration Date, Certificate" },
    { 0x7F4E5F25, "Effective Date, Certificate" },
    { 0x7F4E5F29, "Certificate Profile Identifier" },
    { 0x7F4E65, "Certificate Extensions" },
    { 0x7F60, "Template, Biometric information" },
    { 0x80, "Response Message Template Format 1" },
    { 0x80, "Response Message Template Format 1" },
    { 0x80, "Response Message Template Format 1" },
    { 0x80, "Response Message Template Format 1" },
    { 0x81, "Amount, Authorised (Binary)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x82, "Application Interchange Profile (AIP)" },
    { 0x83, "Command Template" },
    { 0x83, "Command Template" },
    { 0x84, "Dedicated File (DF) Name" },
    { 0x84, "Dedicated File (DF) Name" },
    { 0x84, "Dedicated File (DF) Name" },
    { 0x84, "Dedicated File (DF) Name" },
    { 0x86, "Issuer Script Command" },
    { 0x86, "Issuer Script Command" },
    { 0x87, "Application Priority Indicator" },
    { 0x87, "Application Priority Indicator" },
    { 0x87, "Application Priority Indicator" },
    { 0x87, "Application Priority Indicator" },
    { 0x87, "Application Priority Indicator" },
    { 0x88, "Short File Identifier (SFI)" },
    { 0x88, "Short File Identifier (SFI)" },
    { 0x88, "Short File Identifier (SFI)" },
    { 0x89, "Authorisation Code" },
    { 0x89, "Authorisation Code" },
    { 0x89, "Authorization Code" },
    { 0x8A, "Authorisation Response Code (ARC)" },
    { 0x8A, "Authorisation Response Code (ARC)" },
    { 0x8A, "Authorisation Response Code (ARC)" },
    { 0x8A, "Authorization Response Code (ARC)" },
    { 0x8C, "Card Risk Management Data Object List 1 (CDOL1)" },
    { 0x8C, "Card Risk Management Data Object List 1 (CDOL1)" },
    { 0x8C, "Card Risk Management Data Object List 1 (CDOL1)" },
    { 0x8C, "Card Risk Management Data Object List 1 (CDOL1)" },
    { 0x8D, "Card Risk Management Data Object List 2 (CDOL2)" },
    { 0x8D, "Card Risk Management Data Object List 2 (CDOL2)" },
    { 0x8D, "Card Risk Management Data Object List 2 (CDOL2)" },
    { 0x8E, "Cardholder Verification Method (CVM) List" },
    { 0x8E, "Cardholder Verification Method (CVM) List" },
    { 0x8E, "Cardholder Verification Method (CVM) List" },
    { 0x8E, "Cardholder Verification Method (CVM) List" },
    { 0x8F, "Certification Authority Public Key Index (PKI)" },
    { 0x8F, "Certification Authority Public Key Index (PKI)" },
    { 0x8F, "Certification Authority Public Key Index (PKI)" },
    { 0x8F, "Certification Authority Public Key Index (PKI)" },
    { 0x8F, "Certification Authority Public Key Index (PKI)" },
    { 0x90, "Issuer Public Key Certificate" },
    { 0x90, "Issuer Public Key Certificate" },
    { 0x90, "Issuer Public Key Certificate" },
    { 0x90, "Issuer Public Key Certificate" },
    { 0x90, "Issuer Public Key Certificate" },
    { 0x91, "Issuer Authentication Data" },
    { 0x91, "Issuer Authentication Data" },
    { 0x91, "Issuer Authentication Data" },
    { 0x91, "Issuer Authentication Data" },
    { 0x92, "Issuer Public Key Remainder" },
    { 0x92, "Issuer Public Key Remainder" },
    { 0x92, "Issuer Public Key Remainder" },
    { 0x92, "Issuer Public Key Remainder" },
    { 0x92, "Issuer Public Key Remainder" },
    { 0x93, "Signed Static Application Data (SAD)" },
    { 0x93, "Signed Static Application Data (SAD)" },
    { 0x94, "Application File Locator (AFL)" },
    { 0x94, "Application File Locator (AFL)" },
    { 0x94, "Application File Locator (AFL)" },
    { 0x94, "Application File Locator (AFL)" },
    { 0x94, "Application File Locator (AFL)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x95, "Terminal Verification Results (TVR)" },
    { 0x97, "Transaction Certificate Data Object List (TDOL)" },
    { 0x98, "Transaction Certificate (TC) Hash Value" },
    { 0x99, "Transaction Personal Identification Number (PIN) Data" },
    { 0x9A, "Transaction Date" },
    { 0x9A, "Transaction Date" },
    { 0x9A, "Transaction Date" },
    { 0x9A, "Transaction Date" },
    { 0x9A, "Transaction Date" },
    { 0x9A, "Transaction Date" },
    { 0x9B, "Transaction Status Information (TSI)" },
    { 0x9C, "Transaction Type" },
    { 0x9C, "Transaction Type" },
    { 0x9C, "Transaction Type" },
    { 0x9C, "Transaction Type" },
    { 0x9C, "Transaction Type" },
    { 0x9C, "Transaction Type" },
    { 0x9D, "Directory Definition File (DDF) Name" },
    { 0x9F01, "Acquirer Identifier" },
    { 0x9F01, "Acquirer Identifier" },
    { 0x9F01, "Acquirer Identifier" },
    { 0x9F02, "Amount, Authorised (Numeric)" },
    { 0x9F02, "Amount, Authorised (Numeric)" },
    { 0x9F02, "Amount, Authorised (Numeric)" },
    { 0x9F02, "Amount, Authorised (Numeric)" },
    { 0x9F02, "Amount, Authorised (Numeric)" },
    { 0x9F02, "Authorised Amount (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F03, "Amount, Other (Numeric)" },
    { 0x9F04, "Amount, Other (Binary)" },
    { 0x9F05, "Application Discretionary Data" },
    { 0x9F06, "Application Identifier (AID), Terminal" },
    { 0x9F06, "Application Identifier (AID), Terminal" },
    { 0x9F07, "Application Usage Control (AUC)" },
    { 0x9F07, "Application Usage Control (AUC)" },
    { 0x9F07, "Application Usage Control (AUC)" },
    { 0x9F07, "Application Usage Control (AUC)" },
    { 0x9F07, "Application Usage Control (AUC)" },
    { 0x9F08, "Application Version Number" },
    { 0x9F08, "Application Version Number" },
    { 0x9F08, "Application Version Number, Card" },
    { 0x9F09, "Application Version Number" },
    { 0x9F09, "Application Version Number, Terminal" },
    { 0x9F0B, "Cardholder Name - Extended" },
    { 0x9F0D, "Issuer Action Code - Default" },
    { 0x9F0D, "Issuer Action Code - Default" },
    { 0x9F0D, "Issuer Action Code - Default" },
    { 0x9F0D, "Issuer Action Code - Default" },
    { 0x9F0E, "Issuer Action Code - Denial" },
    { 0x9F0E, "Issuer Action Code - Denial" },
    { 0x9F0E, "Issuer Action Code - Denial" },
    { 0x9F0E, "Issuer Action Code - Denial" },
    { 0x9F0F, "Issuer Action Code - Online" },
    { 0x9F0F, "Issuer Action Code - Online" },
    { 0x9F0F, "Issuer Action Code - Online" },
    { 0x9F0F, "Issuer Action Code - Online" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F10, "Issuer Application Data (IAD)" },
    { 0x9F11, "Issuer Code Table Index" },
    { 0x9F11, "Issuer Code Table Index" },
    { 0x9F11, "Issuer Code Table Index" },
    { 0x9F11, "Issuer Code Table Index" },
    { 0x9F12, "Application Preferred Name" },
    { 0x9F12, "Application Preferred Name" },
    { 0x9F12, "Application Preferred Name" },
    { 0x9F12, "Application Preferred Name" },
    { 0x9F13, "Last Online Application Transaction Counter (ATC) Register" },
    { 0x9F14, "Lower Consecutive Offline Limit (LCOL)" },
    { 0x9F15, "Merchant Category Code (MCC)" },
    { 0x9F15, "Merchant Category Code (MCC)" },
    { 0x9F15, "Merchant Category Code (MCC)" },
    { 0x9F16, "Merchant Identifier" },
    { 0x9F16, "Merchant Identifier" },
    { 0x9F17, "Personal Identification Number (PIN) Try Counter" },
    { 0x9F18, "Issuer Script Identifier" },
    { 0x9F18, "Issuer Script Identifier" },
    { 0x9F18, "Issuer Script Identifier" },
    { 0x9F19, "Deleted (see 9F49)" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1A, "Terminal Country Code" },
    { 0x9F1B, "Terminal Floor Limit" },
    { 0x9F1B, "Terminal Floor Limit" },
    { 0x9F1B, "Terminal Floor Limit" },
    { 0x9F1C, "Terminal Identification" },
    { 0x9F1C, "Terminal Identification" },
    { 0x9F1D, "Terminal Risk Management Data" },
    { 0x9F1E, "Interface Device (IFD) Serial Number" },
    { 0x9F1E, "Interface Device (IFD) Serial Number" },
    { 0x9F1F, "Track 1 Discretionary Data" },
    { 0x9F1F, "Track 1 Discretionary Data" },
    { 0x9F1F, "Track 1 Discretionary Data" },
    { 0x9F1F, "Track 1 Discretionary Data" },
    { 0x9F1F, "Track 1, Discretionary Data" },
    { 0x9F20, "Track 2 Discretionary Data" },
    { 0x9F20, "Track 2, Discretionary Data" },
    { 0x9F21, "Transaction Time" },
    { 0x9F21, "Transaction Time" },
    { 0x9F21, "Transaction Time" },
    { 0x9F22, "Certification Authority Public Key Index (PKI)" },
    { 0x9F22, "Public Key Index, Certification Authority, Terminal" },
    { 0x9F23, "Upper Consecutive Offline Limit (UCOL)" },
    { 0x9F24,
      "Payment Account Reference (PAR) generated or linked directly to the provision request in the token vault" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F26, "Application Cryptogram (AC)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F27, "Cryptogram Information Data (CID)" },
    { 0x9F29, "Extended Selection" },
    { 0x9F2A, "Kernel Identifier" },
    { 0x9F2D, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate" },
    { 0x9F2E, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent" },
    { 0x9F2F, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder" },
    { 0x9F32, "Issuer Public Key Exponent" },
    { 0x9F32, "Issuer Public Key Exponent" },
    { 0x9F32, "Issuer Public Key Exponent" },
    { 0x9F32, "Issuer Public Key Exponent" },
    { 0x9F32, "Issuer Public Key Exponent" },
    { 0x9F33, "Terminal Capabilities" },
    { 0x9F33, "Terminal Capabilities" },
    { 0x9F33, "Terminal Capabilities" },
    { 0x9F34, "Cardholder Verification Method (CVM) Results" },
    { 0x9F34, "Cardholder Verification Method (CVM) Results" },
    { 0x9F35, "Terminal Type" },
    { 0x9F35, "Terminal Type" },
    { 0x9F35, "Terminal Type" },
    { 0x9F35, "Terminal Type" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F36, "Application Transaction Counter (ATC)" },
    { 0x9F37, "Unpredictable Number (UN)" },
    { 0x9F37, "Unpredictable Number (UN)" },
    { 0x9F37, "Unpredictable Number (UN) (Reader/Terminal)" },
    { 0x9F37, "Unpredictable Number (UN)" },
    { 0x9F37, "Unpredictable Number (UN)" },
    { 0x9F37, "Unpredictable Number (UN)" },
    { 0x9F38, "Processing Options Data Object List (PDOL)" },
    { 0x9F38, "Processing Options Data Object List (PDOL)" },
    { 0x9F38, "Processing Options Data Object List (PDOL)" },
    { 0x9F38, "Processing Options Data Object List (PDOL)" },
    { 0x9F38, "Processing Options Data Object List (PDOL)" },
    { 0x9F39, "Point-of-Service (POS) Entry Mode" },
    { 0x9F3A, "Amount, Reference Currency (Binary)" },
    { 0x9F3B, "Currency Code, Application Reference" },
    { 0x9F3C, "Currency Code, Transaction Reference" },
    { 0x9F3D, "Currency Exponent, Transaction Reference" },
    { 0x9F40, "Additional Terminal Capabilities (ATC)" },
    { 0x9F40, "Additional Terminal Capabilities (ATC)" },
    { 0x9F40, "Additional Terminal Capabilities (ATC)" },
    { 0x9F41, "Transaction Sequence Counter" },
    { 0x9F42, "Currency Code, Application" },
    { 0x9F42, "Currency Code, Application" },
    { 0x9F42, "Currency Code, Application" },
    { 0x9F42, "Currency Code, Application" },
    { 0x9F43, "Currency Exponent, Application Reference" },
    { 0x9F44, "Currency Exponent, Application" },
    { 0x9F44, "Currency Exponent, Application" },
    { 0x9F45, "Data Authentication Code" },
    { 0x9F46, "Integrated Circuit Card (ICC) Public Key Certificate" },
    { 0x9F46, "Integrated Circuit Card (ICC) Public Key Certificate" },
    { 0x9F46, "Application Public Key Certificate" },
    { 0x9F46, "Integrated Circuit Card (ICC) Public Key Certificate" },
    { 0x9F46, "Integrated Circuit Card (ICC) Public Key Certificate" },
    { 0x9F47, "Integrated Circuit Card (ICC) Public Key Exponent" },
    { 0x9F47, "Integrated Circuit Card (ICC) Public Key Exponent" },
    { 0x9F47, "Application Public Key Exponent" },
    { 0x9F47, "Integrated Circuit Card (ICC) Public Key Exponent" },
    { 0x9F47, "Integrated Circuit Card (ICC) Public Key Exponent" },
    { 0x9F48, "Integrated Circuit Card (ICC) Public Key Remainder" },
    { 0x9F48, "Integrated Circuit Card (ICC) Public Key Remainder" },
    { 0x9F48, "Application Public Key Remainder" },
    { 0x9F48, "Integrated Circuit Card (ICC) Public Key Remainder" },
    { 0x9F48, "Integrated Circuit Card (ICC) Public Key Remainder" },
    { 0x9F49, "Dynamic Data Authentication Data Object List (DDOL)" },
    { 0x9F4A, "Static Data Authentication Tag List (SDA)" },
    { 0x9F4A, "Static Data Authentication Tag List (SDA)" },
    { 0x9F4A, "Static Data Authentication Tag List (SDA)" },
    { 0x9F4A, "Static Data Authentication Tag List (SDA)" },
    { 0x9F4A, "Static Data Authentication Tag List (SDA)" },
    { 0x9F4B, "Signed Dynamic Application Data (SDAD)" },
    { 0x9F4B, "Signed Dynamic Application Data (SDAD)" },
    { 0x9F4B, "Signed Dynamic Application Data (SDAD)" },
    { 0x9F4B, "Signed Dynamic Application Data (SDAD)" },
    { 0x9F4C, "ICC Dynamic Number" },
    { 0x9F4C, "ICC Dynamic Number" },
    { 0x9F4D, "Log Entry" },
    { 0x9F4D, "Log Entry" },
    { 0x9F4D, "Log Entry" },
    { 0x9F4E, "Merchant Name and Location" },
    { 0x9F4E, "Merchant Name and Location" },
    { 0x9F4E, "Merchant Name and Location" },
    { 0x9F4E, "Merchant Name and Location" },
    { 0x9F4F, "Log Format" },
    { 0x9F4F, "Log Format" },
    { 0x9F50, "Offline Accumulator Balance" },
    { 0x9F50, "Cardholder Verification Status" },
    { 0x9F51, "Application Currency Code" },
    { 0x9F51, "DRDOL" },
    { 0x9F52, "Application Default Action (ADA)" },
    { 0x9F52, "Terminal Compatibility Indicator" },
    { 0x9F53, "Consecutive Transaction Counter International Limit (CTCIL)" },
    { 0x9F53, "Transaction Category Code" },
    { 0x9F53, "Terminal Interchange Profile (dynamic)" },
    { 0x9F54, "Cumulative Total Transaction Amount Limit (CTTAL)" },
    { 0x9F54, "DS ODS Card" },
    { 0x9F55, "Geographic Indicator" },
    { 0x9F55, "Issuer Authentication Flags" },
    { 0x9F55, "Issuer Authentication Flags" },
    { 0x9F55, "Issuer Authentication Flags" },
    { 0x9F56, "Issuer Authentication Indicator" },
    { 0x9F56, "Issuer Proprietary Bitmap" },
    { 0x9F56, "Issuer Proprietary Bitmap" },
    { 0x9F56, "Issuer Proprietary Bitmap" },
    { 0x9F57, "Issuer Country Code" },
    { 0x9F58, "Consecutive Transaction Counter Limit (CTCL)" },
    { 0x9F59, "Consecutive Transaction Counter Upper Limit (CTCUL)" },
    { 0x9F5A, "Application Program Identifier (Program ID)" },
    { 0x9F5A, "Application Program Identifier (Program ID)" },
    { 0x9F5B, "Issuer Script Results" },
    { 0x9F5B, "DSDOL" },
    { 0x9F5C, "Cumulative Total Transaction Amount Upper Limit (CTTAUL)" },
    { 0x9F5C, "DS Requested Operator ID" },
    { 0x9F5C, "Magstripe Data Object List (MDOL)" },
    { 0x9F5D, "Available Offline Spending Amount (AOSA)" },
    { 0x9F5D, "Application Capabilities Information (ACI)" },
    { 0x9F5E, "Consecutive Transaction International Upper Limit (CTIUL)" },
    { 0x9F5E, "DS ID" },
    { 0x9F5F, "DS Slot Availability" },
    { 0x9F5F, "Offline Balance" },
    { 0x9F60, "CVC3 (Track1)" },
    { 0x9F60, "Issuer Update Parameter" },
    { 0x9F60, "P3 Generated 3DES KEYS" },
    { 0x9F61, "CVC3 (Track2)" },
    { 0x9F62, "PCVC3 (Track1)" },
    { 0x9F62, "Encrypted PIN - ISO 95641 Format 0 (Thales P3 Format 01)" },
    { 0x9F63, "Offline Counter Initial Value" },
    { 0x9F63, "PUNATC (Track1)" },
    { 0x9F64, "NATC (Track1)" },
    { 0x9F65, "PCVC3 (Track2)" },
    { 0x9F66, "Terminal Transaction Qualifiers (TTQ)" },
    { 0x9F66, "PUNATC (Track2)" },
    { 0x9F67, "MSD Offset" },
    { 0x9F67, "NATC (Track2)" },
    { 0x9F68, "Card Additional Processes" },
    { 0x9F69, "Card Authentication Related Data" },
    { 0x9F69, "UDOL" },
    { 0x9F6A, "Unpredictable Number (Numeric)" },
    { 0x9F6B, "Card CVM Limit" },
    { 0x9F6B, "Track 2 Data" },
    { 0x9F6C, "Card Transaction Qualifiers (CTQ)" },
    { 0x9F6D, "VLP Reset Threshold" },
    { 0x9F6D, "Mag-stripe Application Version Number (Reader)" },
    { 0x9F6D, "Kernel 4 Reader Capabilities" },
    { 0x9F6E, "Third Party Data" },
    { 0x9F6E, "Form Factor Indicator (qVSDC)" },
    { 0x9F6E, "Form Factor Indicator (FFI)" },
    { 0x9F6F, "DS Slot Management Control" },
    { 0x9F70, "Protected Data Envelope 1" },
    { 0x9F70, "Card Interface Capabilities" },
    { 0x9F71, "Protected Data Envelope 2" },
    { 0x9F71, "Mobile CVM Results" },
    { 0x9F72, "Protected Data Envelope 3" },
    { 0x9F72, "Consecutive Transaction Limit (International—Country)" },
    { 0x9F73, "Protected Data Envelope 4" },
    { 0x9F73, "Currency Conversion Parameters" },
    { 0x9F74, "Protected Data Envelope 5" },
    { 0x9F74, "VLP Issuer Authorisation Code" },
    { 0x9F75, "Unprotected Data Envelope 1" },
    { 0x9F75, "Cumulative Total Transaction Amount Limit-Dual Currency" },
    { 0x9F76, "Unprotected Data Envelope 2" },
    { 0x9F76, "Secondary Application Currency Code" },
    { 0x9F77, "Unprotected Data Envelope 3" },
    { 0x9F77, "VLP Funds Limit" },
    { 0x9F78, "Unprotected Data Envelope 4" },
    { 0x9F78, "VLP Single Transaction Limit" },
    { 0x9F79, "Unprotected Data Envelope 5" },
    { 0x9F79, "VLP Available Funds" },
    { 0x9F7A, "VLP Terminal Support Indicator" },
    { 0x9F7B, "VLP Terminal Transaction Limit" },
    { 0x9F7C, "Customer Exclusive Data (CED)" },
    { 0x9F7C, "Merchant Custom Data" },
    { 0x9F7D, "DS Summary 1" },
    { 0x9F7D, "VISA Applet Data" },
    { 0x9F7E, "Mobile Support Indicator" },
    { 0x9F7E, "Application life cycle data (8 first bytes)" },
    { 0x9F7F, "DS Unpredictable Number" },
    { 0x9F7F, "Card Production Life Cycle (CPLC) Data" },
    { 0xA5, "File Control Information (FCI) Proprietary Template" },
    { 0xA5, "File Control Information (FCI) Proprietary Template" },
    { 0xA5, "File Control Information (FCI) Proprietary Template" },
    { 0xBF0C, "File Control Information (FCI) Issuer Discretionary Data" },
    { 0xBF0C, "File Control Information (FCI) Issuer Discretionary Data" },
    { 0xBF0C, "File Control Information (FCI) Issuer Discretionary Data" },
    { 0xBF0C, "File Control Information (FCI) Issuer Discretionary Data" },
    { 0xBF50, "Visa Fleet - CDO" },
    { 0xBF60, "Integrated Data Storage Record Update Template" },
    { 0xC3, "Card issuer action code -decline" },
    { 0xC4, "Card issuer action code -default" },
    { 0xC5, "Card issuer action code online" },
    { 0xC6, "PIN Try Limit" },
    { 0xC7, "CDOL 1 Related Data Length" },
    { 0xC8, "Card risk management country code" },
    { 0xC9, "Card risk management currency code" },
    { 0xCA, "Lower cummulative offline transaction amount" },
    { 0xCB, "Upper cumulative offline transaction amount" },
    { 0xCD, "Card Issuer Action Code (PayPass) - Default" },
    { 0xCE, "Card Issuer Action Code (PayPass) - Online" },
    { 0xCF, "Card Issuer Action Code (PayPass) - Decline" },
    { 0xD1, "Currency conversion table" },
    { 0xD2, "Integrated Data Storage Directory (IDSD)" },
    { 0xD3, "Additional check table" },
    { 0xD5, "Application Control" },
    { 0xD6, "Default ARPC response code" },
    { 0xD7, "Application Control (PayPass)" },
    { 0xD8, "AIP (PayPass)" },
    { 0xD9, "AFL (PayPass)" },
    { 0xDA, "Static CVC3-TRACK1" },
    { 0xDB, "Static CVC3-TRACK2" },
    { 0xDC, "IVCVC3-TRACK1" },
    { 0xDD, "IVCVC3-TRACK2" },
    { 0xDF01, "Encrypted PIN Block in Tag 9F62 - ISO 95641 Format 0" },
    { 0xDF02, "PEK Version Number" },
    { 0xDF03, "PIN Try Limit" },
    { 0xDF04, "PIN Try Counter (VSDC Application)" },
    { 0xDF05, "AIP - For VISA Contactless" },
    { 0xDF06, "Products permitted" },
    { 0xDF07, "Offline checks mandated" },
    { 0xDF08, "UDKmac" },
    { 0xDF09, "UDKenc" },
    { 0xDF0B, "Retries Permitted Limit" },
    { 0xDF0C, "Script Message Update" },
    { 0xDF0D, "Fleet Issuer Action Code - Default" },
    { 0xDF0E, "Fleet Issuer Action Code - Denial" },
    { 0xDF0F, "Fleet Issuer Action Code - Online" },
    { 0xDF12, "Vehicle Registration Number" },
    { 0xDF13, "DDA Public Modulus" },
    { 0xDF14, "Driver Name" },
    { 0xDF15, "Driver ID" },
    { 0xDF16, "Max Fill Volume" },
    { 0xDF17, "DDA Public Modulus Length" },
    { 0xDF18, "Mileage" },
    { 0xDF20, "Issuer Proprietary Bitmap (IPB)" },
    { 0xDF21, "Internet Authentication Flag (IAF)" },
    { 0xDF22, "Encrypted PEK - RFU" },
    { 0xDF23, "PEK Key Check Value - RFU" },
    { 0xDF24, "MDK - Key derivation Index" },
    { 0xDF25, "VISA DPA - MDK - Key derivation Index" },
    { 0xDF26, "Encrypted PIN Block - ISO 9564-1 Format 1 PIN Block (Thales P3 Format 05)" },
    { 0xDF40, "qVSDC AIP" },
    { 0xDF41, "VSDC AIP" },
    { 0xDF42, "UDKac" },
    { 0xDF43, "UDKmac" },
    { 0xDF44, "UDKenc" },
    { 0xDF47, "UDKcvc" },
    { 0xDF48, "UDKac KCV" },
    { 0xDF49, "UDKmac KCV" },
    { 0xDF4A, "UDKenc KCV" },
    { 0xDF4B, "UDKcvc KCV" },
    { 0xDF4B, "POS Cardholder Interaction Information" },
    { 0xDF51, "Grand Parent AC" },
    { 0xDF52, "Parent AC" },
    { 0xDF53, "Grand Parent MAC" },
    { 0xDF54, "Parent MAC" },
    { 0xDF55, "Grand Parent ENC" },
    { 0xDF56, "Parent ENC/Terminal Action Code - Default" },
    { 0xDF57, "Terminal Action Code - Decline" },
    { 0xDF60, "DS Input (Card)" },
    { 0xDF60, "DDA Component P" },
    { 0xDF61, "DDA Component Q" },
    { 0xDF61, "DS Digest H" },
    { 0xDF62, "DS ODS Info" },
    { 0xDF62, "DDA Component D1" },
    { 0xDF63, "DDA Component D2" },
    { 0xDF63, "DS ODS Term" },
    { 0xDF64, "DDA Component Q Minus 1 Mod P" },
    { 0xDF65, "DDA Private Exponent" },
    { 0xDF6B, "Paypass Contactless" },
    { 0xDF79, "Dynamic Data Authentication Keys" },
    { 0xDF8101, "DS Summary 2" },
    { 0xDF8102, "DS Summary 3" },
    { 0xDF8104, "Balance Read Before Gen AC" },
    { 0xDF8105, "Balance Read After Gen AC" },
    { 0xDF8106, "Data Needed" },
    { 0xDF8107, "CDOL1 Related Data" },
    { 0xDF8108, "DS AC Type" },
    { 0xDF8109, "DS Input (Term)" },
    { 0xDF810A, "DS ODS Info For Reader" },
    { 0xDF810B, "DS Summary Status" },
    { 0xDF810C, "Kernel ID" },
    { 0xDF810D, "DSVN Term" },
    { 0xDF810E, "Post-Gen AC Put Data Status" },
    { 0xDF810F, "Pre-Gen AC Put Data Status" },
    { 0xDF8110, "Proceed To First Write Flag" },
    { 0xDF8111, "PDOL Related Data" },
    { 0xDF8112, "Tags To Read" },
    { 0xDF8113, "DRDOL Related Data" },
    { 0xDF8114, "Reference Control Parameter" },
    { 0xDF8115, "Error Indication" },
    { 0xDF8116, "User Interface Request Data" },
    { 0xDF8117, "Card Data Input Capability" },
    { 0xDF8118, "CVM Capability - CVM Required" },
    { 0xDF8119, "CVM Capability - No CVM Required" },
    { 0xDF811A, "Default UDOL" },
    { 0xDF811B, "Kernel Configuration" },
    { 0xDF811C, "Max Lifetime of Torn Transaction Log Record" },
    { 0xDF811D, "Max Number of Torn Transaction Log Records" },
    { 0xDF811E, "Mag-stripe CVM Capability - CVM Required" },
    { 0xDF811F, "Security Capability" },
    { 0xDF8120, "Terminal Action Code - Default" },
    { 0xDF8121, "Terminal Action Code - Denial" },
    { 0xDF8122, "Terminal Action Code - Online" },
    { 0xDF8123, "Reader Contactless Floor Limit" },
    { 0xDF8124, "Reader Contactless Transaction Limit (No On-device CVM)" },
    { 0xDF8125, "Reader Contactless Transaction Limit (On-device CVM)" },
    { 0xDF8126, "Reader CVM Required Limit" },
    { 0xDF8127, "Time Out Value" },
    { 0xDF8128, "IDS Status" },
    { 0xDF8129, "Outcome Parameter Set" },
    { 0xDF812A, "DD Card (Track1)" },
    { 0xDF812B, "DD Card (Track2)" },
    { 0xDF812C, "Mag-stripe CVM Capability - No CVM Required" },
    { 0xDF812D, "Message Hold Time" },
    { 0xDF8130, "Hold Time Value" },
    { 0xDF8131, "Phone Message Table" },
    { 0xFF60, "Visa International" },
    { 0xFF62, "Visa Magnetic Stripe" },
    { 0xFF63, "Visa Quick VSDC" },
    { 0xFF8101, "Torn Record" },
    { 0xFF8102, "Tags To Write Before Gen AC" },
    { 0xFF8103, "Tags To Write After Gen AC" },
    { 0xFF8104, "Data To Send" },
    { 0xFF8105, "Data Record" },
    { 0xFF8106, "Discretionary Data" },
};

#endif